<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-DUVPB633" failures="0" tests="1" name="Default test" time="36.219" errors="0" timestamp="12 Nov 2023 16:09:34 GMT">
  <testcase classname="com.somee.railway.Login" name="TC_01_User_Login_With_Valid_Username_And_Password" time="4.445"/>
  <testcase classname="com.somee.railway.Login" name="User_Cant_Create_Account_With_An_Already_Inuse_Email" time="0.0">
    <ignored/>
  </testcase> <!-- User_Cant_Create_Account_With_An_Already_Inuse_Email -->
  <testcase classname="com.somee.railway.Login" name="TC_03_User_Cant_Login_With_Invalid_Password" time="0.0">
    <ignored/>
  </testcase> <!-- TC_03_User_Cant_Login_With_Invalid_Password -->
  <testcase classname="com.somee.railway.Login" name="TC_04_User_Cant_Login_With_Inactive_Account" time="0.0">
    <ignored/>
  </testcase> <!-- TC_04_User_Cant_Login_With_Inactive_Account -->
  <testcase classname="com.somee.railway.Login" name="TC_02_User_Cant_Login_With_Blank_Username" time="0.0">
    <ignored/>
  </testcase> <!-- TC_02_User_Cant_Login_With_Blank_Username -->
  <testcase classname="com.somee.railway.Login" name="TC_03_System_Show_Message_After_Login_With_Wrong_Password_Many_Times" time="0.0">
    <ignored/>
  </testcase> <!-- TC_03_System_Show_Message_After_Login_With_Wrong_Password_Many_Times -->
</testsuite> <!-- Default test -->
